#!/usr/bin/env python3
"""
Utility: write per-agent permission config files into a project's code_path.

Called by planning/launch.py and architect/launch.py before starting a session.
Reads current agent_permissions from SQLite and generates:
  - .claude/settings.json  (Claude Code)
  - .codex/config.toml     (OpenAI Codex CLI)
  - .gemini/settings.json  (Google Gemini CLI)
"""

import json
import sqlite3
from pathlib import Path

REPO_ROOT    = Path(__file__).parent.parent
DEFAULTS_PATH = REPO_ROOT / "ui" / "server" / "config" / "agent-permissions.defaults.json"


def _load_defaults() -> dict:
    return json.loads(DEFAULTS_PATH.read_text())


def _load_permissions(agent: str, db_path: str) -> dict:
    """Return {item_id: state} for a given agent from the DB."""
    conn = sqlite3.connect(db_path)
    rows = conn.execute(
        "SELECT item_id, state FROM agent_permissions WHERE agent = ?", (agent,)
    ).fetchall()
    conn.close()
    return {r[0]: r[1] for r in rows}


# ── Claude ─────────────────────────────────────────────────────────────────────

def write_claude_config(code_path: str, db_path: str) -> None:
    """Write {code_path}/.claude/settings.json with allow/deny arrays."""
    defaults    = _load_defaults()
    permissions = _load_permissions("claude", db_path)
    mappings    = defaults["mappings"]["claude"]

    allow_list: list[str] = []
    deny_list:  list[str] = []

    for item_id, mapping in mappings.items():
        tools = mapping.get("tools", [])
        state = permissions.get(item_id, "deny")
        if state == "allow":
            allow_list.extend(tools)
        else:
            deny_list.extend(tools)

    config = {"permissions": {"allow": allow_list, "deny": deny_list}}

    config_dir = Path(code_path).expanduser() / ".claude"
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "settings.json").write_text(json.dumps(config, indent=2) + "\n")
    print(f"  Wrote .claude/settings.json ({len(allow_list)} allow, {len(deny_list)} deny)")


# ── Codex ──────────────────────────────────────────────────────────────────────

def write_codex_config(code_path: str, db_path: str) -> None:
    """Write {code_path}/.codex/config.toml with sandbox + allowlist settings."""
    defaults    = _load_defaults()
    permissions = _load_permissions("codex", db_path)
    mappings    = defaults["mappings"]["codex"]

    write_allowed = permissions.get("write", "deny") == "allow"
    edit_allowed  = permissions.get("edit",  "deny") == "allow"
    sandbox_mode  = "workspace-write" if (write_allowed or edit_allowed) else "read-only"

    network_enabled = any(
        permissions.get(k, "deny") == "allow"
        for k in ("web_search", "web_fetch")
    )

    # Collect allowed shell commands
    all_cmds: list[str] = []
    wildcard = False
    for item_id, mapping in mappings.items():
        if "shell_cmds" not in mapping:
            continue
        if permissions.get(item_id, "deny") != "allow":
            continue
        cmds = mapping["shell_cmds"]
        if "*" in cmds:
            wildcard = True
            break
        all_cmds.extend(cmds)

    # Collect MCP server tool allows/denies
    mcp: dict[str, dict] = {}
    for item_id, mapping in mappings.items():
        if "mcp_server" not in mapping:
            continue
        server = mapping["mcp_server"]
        tools  = mapping["tools"]
        state  = permissions.get(item_id, "deny")
        mcp.setdefault(server, {"include": [], "exclude": []})
        if state == "allow":
            mcp[server]["include"].extend(tools)
        else:
            mcp[server]["exclude"].extend(tools)

    lines = [
        "# Generated by Scryer — do not edit manually",
        "",
        "[sandbox]",
        f'type = "{sandbox_mode}"',
        f"network = {str(network_enabled).lower()}",
        "",
    ]

    if wildcard:
        lines += ["[approval]", 'policy = "auto"', ""]
    elif all_cmds:
        lines += ["[approval]", 'policy = "on-failure"', ""]
        for cmd in all_cmds:
            lines += ["[[approval.command_allowlist]]", f'command = "{cmd}"', ""]

    for server, tc in mcp.items():
        if tc["include"]:
            lines += [f'[mcp.servers."{server}"]', ""]
            tools_str = ", ".join(f'"{t}"' for t in tc["include"])
            lines += [f"includeTools = [{tools_str}]", ""]
        elif tc["exclude"]:
            lines += [f'[mcp.servers."{server}"]', ""]
            tools_str = ", ".join(f'"{t}"' for t in tc["exclude"])
            lines += [f"excludeTools = [{tools_str}]", ""]

    config_dir = Path(code_path).expanduser() / ".codex"
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "config.toml").write_text("\n".join(lines))
    print(f"  Wrote .codex/config.toml (sandbox={sandbox_mode}, network={network_enabled})")


# ── Gemini ─────────────────────────────────────────────────────────────────────

def write_gemini_config(code_path: str, db_path: str) -> None:
    """Write {code_path}/.gemini/settings.json with tools.core + MCP restrictions."""
    defaults    = _load_defaults()
    permissions = _load_permissions("gemini", db_path)
    mappings    = defaults["mappings"]["gemini"]

    core_tools:    list[str] = []
    exclude_tools: list[str] = []
    shell_allowed: list[str] = []
    mcp: dict[str, dict]     = {}

    for item_id, mapping in mappings.items():
        state = permissions.get(item_id, "deny")

        if "tools" in mapping:
            if state == "allow":
                core_tools.extend(mapping["tools"])
            else:
                exclude_tools.extend(mapping["tools"])

        if "shell_cmds" in mapping and state == "allow":
            cmds = mapping["shell_cmds"]
            if "*" in cmds:
                if "ShellTool" not in core_tools:
                    core_tools.append("ShellTool")
            else:
                shell_allowed.extend(f"ShellTool({c})" for c in cmds)

        if "mcp_server" in mapping:
            server = mapping["mcp_server"]
            tools  = mapping["tools"]
            mcp.setdefault(server, {"includeTools": [], "excludeTools": []})
            if state == "allow":
                mcp[server]["includeTools"].extend(tools)
            else:
                mcp[server]["excludeTools"].extend(tools)

    config: dict = {}
    tools_cfg: dict = {}
    if core_tools:
        tools_cfg["core"] = core_tools
    if exclude_tools:
        tools_cfg["exclude"] = exclude_tools
    if shell_allowed:
        tools_cfg["allowed"] = shell_allowed
    if tools_cfg:
        config["tools"] = tools_cfg

    servers_cfg: dict = {}
    for server, tc in mcp.items():
        entry: dict = {}
        if tc["includeTools"]:
            entry["includeTools"] = tc["includeTools"]
        if tc["excludeTools"]:
            entry["excludeTools"] = tc["excludeTools"]
        if entry:
            servers_cfg[server] = entry
    if servers_cfg:
        config["mcp"] = {"servers": servers_cfg}

    config_dir = Path(code_path).expanduser() / ".gemini"
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "settings.json").write_text(json.dumps(config, indent=2) + "\n")
    print(f"  Wrote .gemini/settings.json ({len(core_tools)} core tools)")


# ── Public API ─────────────────────────────────────────────────────────────────

def write_agent_configs(agent: str, code_path: str, db_path: str) -> None:
    """Write the appropriate config file for the given agent into code_path."""
    if not code_path:
        print("  Skipping agent config: code_path not set")
        return
    if agent == "claude":
        write_claude_config(code_path, db_path)
    elif agent == "codex":
        write_codex_config(code_path, db_path)
    elif agent == "gemini":
        write_gemini_config(code_path, db_path)
    else:
        print(f"  Unknown agent {agent!r}, skipping config write")
